// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd93FI8_Wc7PDZggeZk-zxdY0Xj-KDdWY',
    appId: '1:975538261911:web:aa89da846a8e91cd95fed2',
    messagingSenderId: '975538261911',
    projectId: 'reservo-app-436ff',
    authDomain: 'reservo-app-436ff.firebaseapp.com',
    storageBucket: 'reservo-app-436ff.firebasestorage.app',
    measurementId: 'G-0LX7GS4CTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkgv4GLbxLUgLJbzhhuTpbSzlqkRdwNDA',
    appId: '1:975538261911:android:66ef306e9b36c75195fed2',
    messagingSenderId: '975538261911',
    projectId: 'reservo-app-436ff',
    storageBucket: 'reservo-app-436ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ1UIMvgm16J_kCTstvvpfkJ6hPIrTark',
    appId: '1:975538261911:ios:8094d37b2f059e1a95fed2',
    messagingSenderId: '975538261911',
    projectId: 'reservo-app-436ff',
    storageBucket: 'reservo-app-436ff.firebasestorage.app',
    iosBundleId: 'com.example.bookingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ1UIMvgm16J_kCTstvvpfkJ6hPIrTark',
    appId: '1:975538261911:ios:8094d37b2f059e1a95fed2',
    messagingSenderId: '975538261911',
    projectId: 'reservo-app-436ff',
    storageBucket: 'reservo-app-436ff.firebasestorage.app',
    iosBundleId: 'com.example.bookingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd93FI8_Wc7PDZggeZk-zxdY0Xj-KDdWY',
    appId: '1:975538261911:web:17b3173023216af295fed2',
    messagingSenderId: '975538261911',
    projectId: 'reservo-app-436ff',
    authDomain: 'reservo-app-436ff.firebaseapp.com',
    storageBucket: 'reservo-app-436ff.firebasestorage.app',
    measurementId: 'G-32XC8EZJRN',
  );
}
